ifneq (,$(filter $(CONFIG_MTK_MET),y m))
ORIGIN_SRC := $(if $(filter /%,$(src)),,$(srctree)/)$(src)
override src := $(ORIGIN_SRC)
ccflags-y += -I$(ORIGIN_SRC)/../

obj-$(CONFIG_MTK_MET) := met_mcupm_api.o
endif
